---
title: "milestone_4"
author: "Cade Knox"
date: "10/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(Lahman)
library(pitchRx)
library(tidyverse)
```

```{r Bumgarner pitch chart, message=FALSE}

# able to go into the data of pitchRx and select this one specific appearance for Madison Bumgarner and analyze the pitches he through that were whiffed that day. For the project, I'll do a larger scale combining many pitchers and creating a similar graphic.

dat <- scrape("2014-08-03", "2014-08-03")
locations <- select(dat$pitch, pitch_type, start_speed, px, pz, des, num, gameday_link)
names <- select(dat$atbat, pitcher, batter, pitcher_name, batter_name, num, gameday_link, event, stand)
data <- names %>% filter(pitcher_name == "Madison Bumgarner") %>% inner_join(locations, ., by = c("num", "gameday_link"))

# subset the data, keeping all rows but only columns number 1 through 5 and 13

Bum <- data[,c(1:5, 13)]

# we want to filter for those strikes that were swung on but missed

Bum_swing <- filter(Bum, grepl("Swinging", des)) 

# plots pitches, colors them by speed thrown at

p <- ggplot(Bum_swing, aes(px, pz, color = start_speed))

p <- p + scale_x_continuous(limits = c(-3,3)) + scale_y_continuous(limits = c(0,5)) + annotate("rect", xmin = -1, xmax = 1, ymin = 1.5, ymax = 3.5, color = "black", alpha = 0) + labs(title = "Madison Bumgarner: Swinging Strikes, 8/3/2014") + ylab("Horizontal Location (ft.)") + xlab("Vertical Location (ft): Catcher's View") + labs(color = "Velocity (mph)")

# puts in the title and axis labels

p <- p + geom_point(size = 10, alpha = .65)

# finish formatting

p <- p + theme(axis.title = element_text(size = 15, color = "black", face = "bold")) + theme(plot.title = element_text(size = 20, face = "bold", vjust = 1)) + theme(axis.text = element_text(size = 13, face = "bold", color = "black")) + theme(legend.title = element_text(size = 12)) + theme(legend.text = element_text(size = 12))

p

```

